def write_song_data(chart):
            chart.write("[Song]")
            chart.write("\n")
            chart.write("{")
            chart.write("\n")
            chart.write("Name = \"1TEST\"")
            chart.write("\n")
            chart.write("Artist = \"1TEST\"")
            chart.write("\n")
            chart.write("Charter = \"OSU2CH\"")
            chart.write("\n")
            chart.write("Album = \"1TEST\"")
            chart.write("\n")
            chart.write("Year = \", 1\"")
            chart.write("\n")
            chart.write("Offset = 0")
            chart.write("\n")
            chart.write("Resolution = 192")
            chart.write("\n")
            chart.write("Player2 = bass")
            chart.write("\n")
            chart.write("Difficulty = 0")
            chart.write("\n")
            chart.write("PreviewStart = 0")
            chart.write("\n")
            chart.write("PreviewEnd = 0")
            chart.write("\n")
            chart.write("Genre = \"Anime\"")
            chart.write("\n")
            chart.write("MediaType = \"cd\"")
            chart.write("\n")
            chart.write("MusicStream = \"song.ogg\"")
            chart.write("\n")
            chart.write("}")
            chart.write("\n")