def write_ini(ch_folder_path, map_name, song):
    ini = open(ch_folder_path + "/"+map_name+'/song.ini','w')
    ini.write("[Song]\n")
    ini.write("name = "+map_name+"\n")
    ini.write("artist = 1TEST\n")
    ini.write("album = OSU\n")
    ini.write("genre = Anime\n")
    ini.write("year = 1\n")
    ini.write("song_length = "+str(int(song.duration_seconds*1000))+"\n")
    ini.write("count = 0\n")
    ini.write("diff_band = -1\n")
    ini.write("diff_guitar = -1\n")
    ini.write("diff_bass = -1\n")
    ini.write("diff_drums = -1\n")
    ini.write("diff_keys = -1\n")
    ini.write("diff_guitarghl = -1\n")
    ini.write("diff_bassghl = -1\n")
    ini.write("preview_start_time = 0\n")
    ini.write("frets = 0\n")
    ini.write("charter = OSU2CH\n")
    ini.write("icon = 0\n")

    ini.close()